### ISSUE TITLE
Packager not recognizing package.

### ISSUE THREAD

**Issue by Vynestus** [TheLMiffy1111/PackagedAuto#40] opened 2022-04-19 16:28 UTC
This might be fixed and feel free to set it as resolved, I'm running the mod version 2.0.0.5.
Almost every time I start up the world, I've run into an issue where the ME system does not recognize the packager for a moment. Removing the pattern and putting it back in usually fixes it, but afterwards when I request the item, it allows me to, but once the item is actually requested, the packager creates an item that does not seem to match the unpackagers request. I can still place the item directly into the unpackager, and it will craft as normal, but it doesn't satisfy the crafting request and it stays stuck. 
Sometimes it eventually fixes itself once I mess around with the patterns enough, but I can't find out exactly what fixes it. 
What I have noticed is that the pattern that the packager creates has an extra tag compared to the one it expects, and includes "tag:{__storagedrawers_count: 0}" although I can't seem to figure out why.

**Comment by TheLMiffy1111** [comment] 2022-04-19 18:40
Duplicate of #39 , fixed in 2.0.0.6

**Closed as completed by TheLMiffy1111** 2022-04-19 18:40 UTC
Labels: duplicate
